### ISSUE TITLE
Update dependencies for Angular v12

### ISSUE THREAD

**Issue by elnipa** [vdolek/angular-resize-event#40]
I would love to see updated dependencies for Angular v12. 
https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49

Thanks in advance

**Comment by michaelwalgram** [comment]
Can you tell us roughly when we can expect the update?

**Comment by andreipadolin** [comment]
Seems it is just a npm warning message.
```
npm WARN angular-resize-event@2.1.0 requires a peer of @angular/common@^11.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN angular-resize-event@2.1.0 requires a peer of @angular/core@^11.2.2 but none is installed. You must install peer dependencies yourself.
```

**Comment by labeled** [comment]
We have this issue and do not want to pass the --legacy-peer-deps for npm install because it can cause issues with packages used by other packages that need to be updated. What is the ETA on updating this to support angular 12?

**Comment by aadiene** [comment]
You should think about using **ResizeObserver**.
https://dev.to/christiankohler/how-to-use-resizeobserver-with-angular-9l5

**Comment by vdolek** [comment]
Version 3.0.0 has been released. Migrated to Angular 12 and internally implemented using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver).
