### ISSUE TITLE
CommonJS dependencies

### ISSUE THREAD

**Issue by Samuel-Ayvazyan** [vdolek/angular-resize-event#43]
During production build we will get this:
`Warning: node_modules/angular-resize-event/__ivy_ngcc__/fesm2015/angular-resize-event.js depends on 'css-element-queries'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

Hope this issue can be solved after or during update of "angular-resize-event" for Angular 12, but eliminating usage of 'css-element-queries' can be a separate topic.

Thanks in advance.

**Comment by leomayer** [comment]
Same problem here.... Following the link

https://angular.io/guide/build#configuring-commonjs-dependencies

it mentions clearly to use ECMAScript modules. Would be great if the package could be changed in that direction!

**Comment by kfirufk** [comment]
any updates ?

**Comment by vdolek** [comment]
Version 3.0.0 has been released. Migrated to Angular 12 and internally implemented using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver).
