### ISSUE TITLE
onResized(event: ResizedEvent) is called after app initialization

### ISSUE THREAD

**Issue by gitalvininfo** [vdolek/angular-resize-event#45]
Hi, is it normal that this event is called after app initialization? 

I just want to trigger this event during my resize, however, when try to reload the page, in console, this event gets triggered.

Please tell me if this is intentional.

Thank you.

**Comment by vdolek** [comment]
Hi, this is normal behavior. In new version `3.0.0` you can detect first triggered event with `isFirst` flag.
