### ISSUE TITLE
Angular 13 dependency conflict

### ISSUE THREAD

**Issue by ivancelot** [vdolek/angular-resize-event#49]
I can't to install this package, do it needs an update?

![image](https://user-images.githubusercontent.com/5238400/143718413-d538af39-67c2-47a9-84f5-b027ae706562.png)

**Comment by melino** [comment]
You can --force it: `npm install angular-resize-event --force`

I have tested it with Angular 13.0.2 and it works.

**Comment by kwood-gmr** [comment]
I have just submitted a PR for this.
