### ISSUE TITLE
v3.1 - peerDependencies are creating a conflict

### ISSUE THREAD

**Issue by DDtMM** [vdolek/angular-resize-event#52]
When installing to an angular 13 project I get conflicting per dependencies.  In package.json you have:

```
  "peerDependencies": {
    "@angular/common": "^12.2.0",
    "@angular/core": "^12.2.0"
  },
```

I believe you want something like:
```
  "peerDependencies": {
    "@angular/common": ">= 12.2.0 < 14",
    "@angular/core": ">= 12.2.0 < 14"
  },
```

**Comment by tmtron** [comment]
same for me - it seems the peer dependencies in [projects/angular-resize-event/package.json](https://github.com/vdolek/angular-resize-event/blob/3.1.0/projects/angular-resize-event/package.json#L20) have not been updated
