### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by weberhofer** [vdolek/angular-resize-event#68]
It would be great if your library could support Angular 14, too! Thank you!

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">= 12.2.0 < 14" from angular-resize-event@3.1.1
npm ERR! node_modules/angular-resize-event
npm ERR!   angular-resize-event@"^3.1.1" from the root project

**Comment by shynst** [comment]
It seems to work with Angluar 14.

Please update peer dependencies in `angular-resize-event/projects/angular-resize-event/package.json`

**Comment by shynst** [comment]
I created a pull request:

https://github.com/vdolek/angular-resize-event/pull/69

**Comment by vdolek** [comment]
Done, sorry for the delay.
